% Author Guidelines for SADM: https://onlinelibrary.wiley.com/page/journal/19321872/homepage/forauthors.html

%----------------------------------------------------------------------------------------
%	PACKAGES AND OTHER DOCUMENT CONFIGURATIONS
%----------------------------------------------------------------------------------------

\documentclass[AMS,STIX1COL]{WileyNJD-v2}

\usepackage{amsmath,array,amsfonts}
\usepackage[english]{babel} % Language hyphenation and typographical rules

% \usepackage[hang, small,labelfont=bf,up,textfont=it,up]{caption} % Custom captions
\usepackage{booktabs} % Horizontal rules in tables
\usepackage{subfig} % Sub figures
\usepackage{graphicx} % better graphics
\graphicspath{{/}{images/}}
% \usepackage[dvipsnames]{xcolor} % colors
\PassOptionsToPackage{xcolor}{dvipsnames}

\usepackage{enumitem} % Customized lists
\setlist[itemize]{noitemsep} % Make itemize lists more compact

\usepackage{hyperref} % For hyperlinks in the PDF
\usepackage{nameref} % \Cref command automatically handles figure/table/etc refs



\articletype{Article Type}%

\received{26 April 2016}
\revised{6 June 2016}
\accepted{6 June 2016}

\raggedbottom

\begin{document}

%----------------------------------------------------------------------------------------
%	TITLE/AUTHOR SECTION
%----------------------------------------------------------------------------------------
\title{When is a circle not a circle? Conceptual object recognition using neural networks with applications in forensic footwear analysis %\protect\thanks{}
}

\author[1]{Susan Vanderplas}

\author[2]{Miranda Tilton}

% \author[1]{Jayden Stack}


\authormark{Vanderplas \textsc{et al}}


\address[1]{\orgdiv{Statistics Department}, \orgname{University of Nebraska - Lincoln}, \orgaddress{\state{Nebraska}, \country{United States}}}

\address[2]{\orgdiv{Statistics Department}, \orgname{Iowa State University}, \orgaddress{\state{Iowa}, \country{United States}}}

\corres{*Miranda Tilton, 
2438 OSBORN DR, AMES, IA 50011-1090 \email{tiltonm@iastate.edu}}

% \presentaddress{350 Hardin Hall (North Wing), 
% 3310 Holdrege Street, 
% University of Nebraska-Lincoln,
% Lincoln NE 68583-0972}

%----------------------------------------------------------------------------------------


%----------------------------------------------------------------------------------------
%	Front Matter
%----------------------------------------------------------------------------------------
\abstract[Summary]{This is sample abstract text.}

\keywords{keyword1, keyword2, keyword3, keyword4}

\jnlcitation{\cname{%
\author{S. Vanderplas}, 
\author{M. Tilton}} (\cyear{2022}), 
\ctitle{When is a circle not a circle? Conceptual object recognition using neural networks with applications in forensic footwear analysis}, \cjournal{Statistical Analysis and Data Mining}, \cvol{2022;00:1--6}.}

\maketitle

\footnotetext{\textbf{Abbreviations:} Convolutional Neural Net (CNN)}

%----------------------------------------------------------------------------------------

<<setup, include = F>>=
library(knitr)
library(tidyverse)

knitr::opts_chunk$set(dev=c('postscript', 'png'),
                      fig.path = "images/")
@

\section{Introduction}
% Frame the problem - it's hard to identify general concepts like "circle" or "zig-zag" in images, whether you're using old-style methods or newer neural network approaches.

% Talk about the multiple-view one-object problem - this is not just a problem in machine learning, but in life. Our brains solved it, but how?

% Transition into CNNs - structure is similar to the basic understanding of the architecture of the visual cortex, but are CNNs capable of recognizing these generic shapes in very narrow contexts (like footwear patterns)

\subsection{Convolutional Neural Networks for Image Recognition}
% Provide a brief overview of CNNs for image recognition and how they work


% Note that there is rapid development in the field, and innovations like R-CNNs, YOLO, etc. do change the game a little but are still primarily trained for highly specific categories, rather than general concepts.


\subsection{Forensic Footwear Analysis}
% Provide some motivation for the application area - not much data, we can collect data with innovation in machinery, but we still have to be able to automatically *process* that much data, because it's too much to do by hand.

% Emphasize the need to have recognizable categories for examiners' use

\section{Neural Network Model Development}
% General introduction to the approach

\subsection{Transfer Learning}
% Describe VGG16 and why transfer learning is the approach we thought was best here


\subsection{Initial Data}
% Explain how the shoe images were obtained and why we're using them instead of waiting for images from the shoe scanner - e.g. proof-of-concept, concern over general feature recognition as a problem, desire to have a model that can then be adapted to fuzzier/messier data by selectively loosening weights without fully retraining...

\subsection{Classification and Labeling}
% Describe the process of labeling the data, and the specific criteria for each section

The categories we use in this study are operationally defined as follows:
\begin{description}
\item [Bowtie] Bowtie shapes are roughly quadrilateral, with two opposite concave faces. The remaining two faces can be convex or straight, and the concave faces may have straight portions, so long as there is a concave region.
\item [Chevron] Chevron shapes include repeating parallel lines as well as individual ``v" shapes. They may be angular but can also be curved.
\item [Circle] Circles include ellipses and ovals; they must be round.
\item [Line] Lines are repeated and parallel; a more general definition of a line would be difficult to differentiate from many other patterns. Lines can be mildly curved.
\item [Polygon] Polygons are defined in this standard to have more than 4 sides. They include pentagons, hexagons, and octagons.
\item [Quadrilateral] Quadrilaterals (quads) have four sides. They may have rounded or square corners.
\item [Star] Stars are any shape with alternating concave and convex regions, or lines which emanate from a central point. ``X" and ``+" shapes are also classified as stars.
\item [Text] Text is any shape which would be identified as text by a reasonable human. In most cases, the text on the outsole images used is made up of Latin alphabet characters; the model will likely not recognize text in other scripts (but could be trained if non-Latin text images could be obtained).
\item [Triangle] Triangles are any three-sided figure. Like quadrilaterals, they can have rounded corners. In some cases, it is difficult to distinguish between a trapezoidal shape and a triangle when rounded corners are involved.
\item [Other] Other features which were marked include logos, various textures (including crepe, stippling, etc.), and smooth regions with no discernible features. These regions are grouped and provide the additional information that none of the previous nine categories are present.
\end{description}

\begin{center}
\begin{table}
\centering

\caption[Geometric elements used to classify tread patterns.]{A set of geometric elements used to classify tread patterns. Categories modified from \cite{grossVariabilitySignificanceClass2013}.}\label{tab:class-char-examples}

\setlength\tabcolsep{1mm}
\begin{tabular}{rccl}
Bowtie & \raisebox{-.5\height}{\includegraphics[width=.3\textwidth]{class_examples/bowtie_examples.png}} &
\raisebox{-.5\height}{\includegraphics[width=.3\textwidth]{class_examples/chevron_examples.png}} & Chevron \vspace{1mm}\\
Circle & \raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/circle_examples.png}} &
\raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/line_examples.png}} & Line  \vspace{1mm}\\
Polygon & \raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/polygon_examples.png}} &
\raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/quad_examples.png}} & Quad  \vspace{1mm}\\
Star & \raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/star_examples.png}} &
\raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/text_examples.png}} & Text  \vspace{1mm}\\
Triangle & \raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/triangle_examples.png}} &
\raisebox{-.5\height}{\includegraphics[width=0.3\textwidth]{class_examples/other_examples.png}} & Other \\
\end{tabular}
\end{table}
\end{center}

\subsection{Training Data} 
% Describe the training data we used

% Need to make sure training data is properly split up - can't have data from the same image in both the training and test set

\subsection{Model Training}
% Describe model training process - loss function, gradient settings, learning rate, convergence

% Be sure to describe any diagnostics that show that the model is not overfit

\section{Results}

\subsection{Accuracy}
% Describe overall accuracy

% Describe class-by-class accuracy

% Show examples of classifications

\subsection{Shape Generalization}

% Show examples of shape confusion - text vs. circle, triangle vs. quad vs. hexagon

% Show confusion matrix

\subsection{Model Diagnostics}
% Describe diagnostic plots used to "see" what the model sees

\subsubsection{Application: Image Contrast}
% Describe image contrast adaptation, show diagnostics and improvement

\subsubsection{Feature Overlap}
% Show examples and talk about how the model is correctly recognizing features, but is not correctly integrating lower-level features into shapes that are meaningful in this context -- like circles vs quadrilaterals

\section{Conclusions}

% Point 1 - the model is very good at picking out appropriate low-level features that may be aggregated into the correct shape, thanks in part to transfer learning from VGG16

% Point 2 - the model is not particularly good at aggregating these lower-level features into higher-level categories that are sufficiently general that they match our labels

% Point 3 - this is a hard problem - use Seychelles image to show that there are multiple curves that would seem to comprise a circle, but because the figure isn't closed, it isn't a circle. 

% Resolution - May want to try other, newer models, but the fundamental problem remains the same - how do we add in sufficient spatial context to be able to appropriately integrate the features? Discuss a few other options...



%\backmatter

\section*{Acknowledgments}
This work was funded (or partially funded) by the Center for Statistics and Applications in Forensic Evidence (CSAFE) through Cooperative Agreements 70NANB15H176 and 70NANB20H019 between NIST and Iowa State University, which includes activities carried out at Carnegie Mellon University, Duke University, University of California Irvine, University of Virginia, West Virginia University, University of Pennsylvania, Swarthmore College and University of Nebraska, Lincoln.

\subsection*{Author contributions}


\subsection*{Financial disclosure}

% None reported.

\subsection*{Conflict of interest}

% The authors declare no potential conflict of interests.


\section*{Supporting information}

% The following supporting information is available as part of the online article:



\appendix


\bibliography{refs}%


\section*{Author Biography}

\begin{biography}{%
% \includegraphics[width=60pt,height=70pt,draft]{empty}
}{%
\textbf{Author Name.} 
Biography text
}%
\end{biography}

\end{document}
